1. 다중 catch문:try 블록 내부는 다양한 종류의 예외가 발생할 수 있다.
2.해당 예외가 발생할 때 마다 해당 catch문에서 예외 객체를 받아 실행한다.
3. 그러나 먼저 발생할 예외가 단하나의 catch 문만을 실행하고
나머지catch문은 실행되지 않는다.